export const transcript = {
  result: {
    result_index: 0,
    results: [
      {
        final: true,
        end_of_utterance: 'silence',
        alternatives: [
          {
            transcript: 'K. ',
            confidence: 0.61,
            timestamps: [['K.', 2.34, 2.71]],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'silence',
        alternatives: [
          {
            transcript: 'there will come a time where all of us at the ',
            confidence: 0.56,
            timestamps: [
              ['there', 3.59, 3.84],
              ['will', 3.84, 4.14],
              ['come', 4.14, 4.33],
              ['a', 4.33, 4.4],
              ['time', 4.4, 5.09],
              ['where', 5.23, 5.47],
              ['all', 5.58, 6],
              ['of', 6, 6.22],
              ['us', 6.22, 6.44],
              ['at', 6.44, 6.59],
              ['the', 6.59, 6.86],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'silence',
        alternatives: [
          {
            transcript: 'all of us ',
            confidence: 0.92,
            timestamps: [
              ['all', 9.19, 9.48],
              ['of', 9.48, 9.62],
              ['us', 9.62, 9.89],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'silence',
        alternatives: [
          {
            transcript: 'there will come a time and Knowles your mind P. ',
            confidence: 0.61,
            timestamps: [
              ['%HESITATION', 11.28, 12.53],
              ['there', 13.06, 13.26],
              ['will', 13.26, 13.39],
              ['come', 13.39, 13.58],
              ['a', 13.58, 13.65],
              ['time', 13.65, 14.23],
              ['and', 14.23, 14.48],
              ['%HESITATION', 14.48, 14.7],
              ['Knowles', 14.7, 15.62],
              ['your', 15.62, 15.77],
              ['mind', 15.77, 16.4],
              ['P.', 16.76, 17.16],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'silence',
        alternatives: [
          {
            transcript:
              'remaining to remember that anyone ever existed but that all species have added anything ',
            confidence: 0.54,
            timestamps: [
              ['remaining', 19.33, 19.89],
              ['to', 19.89, 20.01],
              ['remember', 20.01, 20.6],
              ['that', 20.6, 20.84],
              ['anyone', 20.99, 21.48],
              ['ever', 21.51, 21.74],
              ['existed', 21.74, 22.44],
              ['but', 23.09, 23.2],
              ['that', 23.2, 23.36],
              ['all', 23.36, 23.53],
              ['species', 23.53, 24.1],
              ['have', 24.1, 24.27],
              ['added', 24.27, 24.55],
              ['anything', 24.55, 25.09],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'full_stop',
        alternatives: [
          {
            transcript:
              'though it be no one left to remember I responsible corporate try that ',
            confidence: 0.6,
            timestamps: [
              ['though', 25.9, 26.09],
              ['it', 26.09, 26.21],
              ['be', 26.21, 26.35],
              ['no', 26.35, 26.51],
              ['one', 26.51, 26.71],
              ['left', 26.71, 27.12],
              ['to', 27.12, 27.21],
              ['remember', 27.21, 27.71],
              ['I', 27.71, 27.83],
              ['responsible', 27.83, 28.41],
              ['corporate', 28.41, 28.79],
              ['try', 28.79, 29.14],
              ['that', 29.64, 29.85],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'full_stop',
        alternatives: [
          {
            transcript: 'hello and you everything everything and do all ',
            confidence: 0.8,
            timestamps: [
              ['hello', 29.88, 30.13],
              ['and', 30.13, 30.3],
              ['you', 30.3, 30.67],
              ['everything', 31.36, 31.79],
              ['everything', 31.79, 32.3],
              ['%HESITATION', 32.94, 33.65],
              ['and', 33.65, 34.05],
              ['do', 34.05, 34.18],
              ['all', 34.18, 34.59],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'full_stop',
        alternatives: [
          {
            transcript:
              'and wrote and Paul and discover the **** off and all of this ',
            confidence: 0.68,
            timestamps: [
              ['and', 35.05, 35.28],
              ['wrote', 35.28, 35.46],
              ['%HESITATION', 35.46, 35.77],
              ['and', 36.29, 36.61],
              ['Paul', 36.61, 36.78],
              ['and', 36.78, 37.06],
              ['discover', 37.06, 37.47],
              ['the', 37.62, 37.75],
              ['****', 37.75, 37.95],
              ['off', 37.95, 38.1],
              ['%HESITATION', 38.1, 38.4],
              ['and', 38.44, 38.71],
              ['all', 38.74, 39.01],
              ['of', 39.01, 39.23],
              ['this', 39.23, 39.63],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'full_stop',
        alternatives: [
          {
            transcript:
              'go head B. bundle if you decide his cover and maybe millions of yes every ',
            confidence: 0.63,
            timestamps: [
              ['go', 39.66, 39.79],
              ['head', 39.79, 40.06],
              ['B.', 40.06, 40.32],
              ['bundle', 40.39, 40.81],
              ['if', 41.53, 41.69],
              ['you', 41.69, 41.79],
              ['decide', 41.79, 42.18],
              ['his', 42.18, 42.34],
              ['cover', 42.34, 42.65],
              ['and', 43.07, 43.26],
              ['maybe', 43.26, 43.56],
              ['%HESITATION', 43.59, 43.89],
              ['millions', 44, 44.44],
              ['of', 44.44, 44.61],
              ['yes', 44.61, 44.85],
              ['every', 44.85, 45.28],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'silence',
        alternatives: [
          {
            transcript: 'but even if you survive the collapse of all sun ',
            confidence: 0.49,
            timestamps: [
              ['but', 45.43, 45.6],
              ['even', 45.6, 45.88],
              ['if', 45.88, 46.01],
              ['you', 46.01, 46.11],
              ['survive', 46.11, 46.5],
              ['the', 46.5, 46.6],
              ['collapse', 46.6, 47.02],
              ['of', 47.02, 47.16],
              ['all', 47.16, 47.35],
              ['sun', 47.35, 47.82],
            ],
          },
        ],
      },
      {
        final: true,
        end_of_utterance: 'silence',
        alternatives: [
          {
            transcript: '54 ',
            confidence: 0.89,
            timestamps: [
              ['%HESITATION', 49.42, 51.07],
              ['%HESITATION', 51.47, 51.9],
              ['five', 52.53, 53.08],
              ['four', 53.32, 53.66],
            ],
          },
        ],
      },
    ],
    speaker_labels: [
      {
        from: 2.34,
        to: 2.71,
        speaker: 1,
        confidence: 0.34,
        final: false,
      },
      {
        from: 3.59,
        to: 3.84,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 3.84,
        to: 4.14,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 4.14,
        to: 4.33,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 4.33,
        to: 4.4,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 4.4,
        to: 5.09,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 5.23,
        to: 5.47,
        speaker: 1,
        confidence: 0.33,
        final: false,
      },
      {
        from: 5.58,
        to: 6,
        speaker: 1,
        confidence: 0.51,
        final: false,
      },
      {
        from: 6,
        to: 6.22,
        speaker: 1,
        confidence: 0.51,
        final: false,
      },
      {
        from: 6.22,
        to: 6.44,
        speaker: 1,
        confidence: 0.51,
        final: false,
      },
      {
        from: 6.44,
        to: 6.59,
        speaker: 1,
        confidence: 0.51,
        final: false,
      },
      {
        from: 6.59,
        to: 6.86,
        speaker: 1,
        confidence: 0.51,
        final: false,
      },
      {
        from: 9.19,
        to: 9.48,
        speaker: 1,
        confidence: 0.54,
        final: false,
      },
      {
        from: 9.48,
        to: 9.62,
        speaker: 1,
        confidence: 0.54,
        final: false,
      },
      {
        from: 9.62,
        to: 9.89,
        speaker: 1,
        confidence: 0.54,
        final: false,
      },
      {
        from: 11.28,
        to: 12.53,
        speaker: 1,
        confidence: 0.5,
        final: false,
      },
      {
        from: 13.06,
        to: 13.26,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 13.26,
        to: 13.39,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 13.39,
        to: 13.58,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 13.58,
        to: 13.65,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 13.65,
        to: 14.23,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 14.23,
        to: 14.48,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 14.48,
        to: 14.7,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 14.7,
        to: 15.62,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 15.62,
        to: 15.77,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 15.77,
        to: 16.4,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 16.76,
        to: 17.16,
        speaker: 1,
        confidence: 0.33,
        final: false,
      },
      {
        from: 19.33,
        to: 19.89,
        speaker: 1,
        confidence: 0.43,
        final: false,
      },
      {
        from: 19.89,
        to: 20.01,
        speaker: 1,
        confidence: 0.43,
        final: false,
      },
      {
        from: 20.01,
        to: 20.6,
        speaker: 1,
        confidence: 0.43,
        final: false,
      },
      {
        from: 20.6,
        to: 20.84,
        speaker: 1,
        confidence: 0.43,
        final: false,
      },
      {
        from: 20.99,
        to: 21.48,
        speaker: 1,
        confidence: 0.35,
        final: false,
      },
      {
        from: 21.51,
        to: 21.74,
        speaker: 1,
        confidence: 0.35,
        final: false,
      },
      {
        from: 21.74,
        to: 22.44,
        speaker: 1,
        confidence: 0.35,
        final: false,
      },
      {
        from: 23.09,
        to: 23.2,
        speaker: 1,
        confidence: 0.36,
        final: false,
      },
      {
        from: 23.2,
        to: 23.36,
        speaker: 1,
        confidence: 0.36,
        final: false,
      },
      {
        from: 23.36,
        to: 23.53,
        speaker: 1,
        confidence: 0.36,
        final: false,
      },
      {
        from: 23.53,
        to: 24.1,
        speaker: 1,
        confidence: 0.36,
        final: false,
      },
      {
        from: 24.1,
        to: 24.27,
        speaker: 1,
        confidence: 0.36,
        final: false,
      },
      {
        from: 24.27,
        to: 24.55,
        speaker: 1,
        confidence: 0.36,
        final: false,
      },
      {
        from: 24.55,
        to: 25.09,
        speaker: 1,
        confidence: 0.36,
        final: false,
      },
      {
        from: 25.9,
        to: 26.09,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 26.09,
        to: 26.21,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 26.21,
        to: 26.35,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 26.35,
        to: 26.51,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 26.51,
        to: 26.71,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 26.71,
        to: 27.12,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 27.12,
        to: 27.21,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 27.21,
        to: 27.71,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 27.71,
        to: 27.83,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 27.83,
        to: 28.41,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 28.41,
        to: 28.79,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 28.79,
        to: 29.14,
        speaker: 1,
        confidence: 0.44,
        final: false,
      },
      {
        from: 29.64,
        to: 29.85,
        speaker: 1,
        confidence: 0.38,
        final: false,
      },
      {
        from: 29.88,
        to: 30.13,
        speaker: 1,
        confidence: 0.47,
        final: false,
      },
      {
        from: 30.13,
        to: 30.3,
        speaker: 1,
        confidence: 0.47,
        final: false,
      },
      {
        from: 30.3,
        to: 30.67,
        speaker: 1,
        confidence: 0.47,
        final: false,
      },
      {
        from: 31.36,
        to: 31.79,
        speaker: 1,
        confidence: 0.45,
        final: false,
      },
      {
        from: 31.79,
        to: 32.3,
        speaker: 1,
        confidence: 0.45,
        final: false,
      },
      {
        from: 32.94,
        to: 33.65,
        speaker: 1,
        confidence: 0.37,
        final: false,
      },
      {
        from: 33.65,
        to: 34.05,
        speaker: 1,
        confidence: 0.37,
        final: false,
      },
      {
        from: 34.05,
        to: 34.18,
        speaker: 1,
        confidence: 0.37,
        final: false,
      },
      {
        from: 34.18,
        to: 34.59,
        speaker: 1,
        confidence: 0.37,
        final: false,
      },
      {
        from: 35.05,
        to: 35.28,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 35.28,
        to: 35.46,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 35.46,
        to: 35.77,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 36.29,
        to: 36.61,
        speaker: 1,
        confidence: 0.42,
        final: false,
      },
      {
        from: 36.61,
        to: 36.78,
        speaker: 1,
        confidence: 0.42,
        final: false,
      },
      {
        from: 36.78,
        to: 37.06,
        speaker: 1,
        confidence: 0.42,
        final: false,
      },
      {
        from: 37.06,
        to: 37.47,
        speaker: 1,
        confidence: 0.42,
        final: false,
      },
      {
        from: 37.62,
        to: 37.75,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 37.75,
        to: 37.95,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 37.95,
        to: 38.1,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 38.1,
        to: 38.4,
        speaker: 1,
        confidence: 0.39,
        final: false,
      },
      {
        from: 38.44,
        to: 38.71,
        speaker: 1,
        confidence: 0.41,
        final: false,
      },
      {
        from: 38.74,
        to: 39.01,
        speaker: 1,
        confidence: 0.57,
        final: false,
      },
      {
        from: 39.01,
        to: 39.23,
        speaker: 1,
        confidence: 0.57,
        final: false,
      },
      {
        from: 39.23,
        to: 39.63,
        speaker: 1,
        confidence: 0.57,
        final: false,
      },
      {
        from: 39.66,
        to: 39.79,
        speaker: 1,
        confidence: 0.49,
        final: false,
      },
      {
        from: 39.79,
        to: 40.06,
        speaker: 1,
        confidence: 0.49,
        final: false,
      },
      {
        from: 40.06,
        to: 40.32,
        speaker: 1,
        confidence: 0.49,
        final: false,
      },
      {
        from: 40.39,
        to: 40.81,
        speaker: 1,
        confidence: 0.51,
        final: false,
      },
      {
        from: 41.53,
        to: 41.69,
        speaker: 1,
        confidence: 0.5,
        final: false,
      },
      {
        from: 41.69,
        to: 41.79,
        speaker: 1,
        confidence: 0.5,
        final: false,
      },
      {
        from: 41.79,
        to: 42.18,
        speaker: 1,
        confidence: 0.5,
        final: false,
      },
      {
        from: 42.18,
        to: 42.34,
        speaker: 1,
        confidence: 0.5,
        final: false,
      },
      {
        from: 42.34,
        to: 42.65,
        speaker: 1,
        confidence: 0.5,
        final: false,
      },
      {
        from: 43.07,
        to: 43.26,
        speaker: 1,
        confidence: 0.42,
        final: false,
      },
      {
        from: 43.26,
        to: 43.56,
        speaker: 1,
        confidence: 0.42,
        final: false,
      },
      {
        from: 43.59,
        to: 43.89,
        speaker: 1,
        confidence: 0.42,
        final: false,
      },
      {
        from: 44,
        to: 44.44,
        speaker: 1,
        confidence: 0.33,
        final: false,
      },
      {
        from: 44.44,
        to: 44.61,
        speaker: 1,
        confidence: 0.33,
        final: false,
      },
      {
        from: 44.61,
        to: 44.85,
        speaker: 1,
        confidence: 0.33,
        final: false,
      },
      {
        from: 44.85,
        to: 45.28,
        speaker: 1,
        confidence: 0.33,
        final: false,
      },
      {
        from: 45.43,
        to: 45.6,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 45.6,
        to: 45.88,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 45.88,
        to: 46.01,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 46.01,
        to: 46.11,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 46.11,
        to: 46.5,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 46.5,
        to: 46.6,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 46.6,
        to: 47.02,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 47.02,
        to: 47.16,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 47.16,
        to: 47.35,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 47.35,
        to: 47.82,
        speaker: 1,
        confidence: 0.48,
        final: false,
      },
      {
        from: 49.42,
        to: 51.07,
        speaker: 1,
        confidence: 0.56,
        final: false,
      },
      {
        from: 51.47,
        to: 51.9,
        speaker: 1,
        confidence: 0.52,
        final: false,
      },
      {
        from: 52.53,
        to: 53.08,
        speaker: 1,
        confidence: 0.5,
        final: false,
      },
      {
        from: 53.32,
        to: 53.66,
        speaker: 1,
        confidence: 0.6,
        final: true,
      },
    ],
  },
};
