import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';

import { createFFmpeg, fetchFile } from '@ffmpeg/ffmpeg';
import { cleanClip } from '../components/editor/clip-handlers/cleanClip';
import { convertToClip } from '../components/editor/clip-handlers/convertToClip';
import { transcribeClip } from '../components/editor/clip-handlers/transcribeToClip';

const ffmpeg = createFFmpeg({
  corePath: '/ffmpeg-core/ffmpeg-core.js',
});
export default function Home() {
  const [ready, setReady] = useState(false);
  const [video, setVideo] = useState();
  const [gif, setGif] = useState();
  const [clip, setClip] = useState();
  const [images, setImages] = useState();
  const [cleanedClip, setCleanedClip] = useState();
  const [transcription, setTranscription] = useState();

  const IMPORTFILENAME = 'test.mp4';
  const AUDIOFILENAME = 'test.aac';
  const SILENCESFILENAME = 'silence.txt';
  const PROCESSEDAUDIOFN = 'finalcut.mp4';
  let CONCATFILENAME = '';

  const load = async () => {
    await ffmpeg.load();
    setReady(true);
  };

  useEffect(() => {
    load();
  }, []); // only called once

  return (
    <div className={styles.container}>
      <Head>
        <title>SuccinctCut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Succinct Cut</h1>
        {ready ? (
          <div className="App">
            {video && (
              <video
                controls
                width="250"
                src={URL.createObjectURL(video)}
              ></video>
            )}
            <input
              type="file"
              onChange={(e) => {
                setVideo(e.target.files?.item(0));
                console.log(
                  'e.target.files?.item(0) :>> ',
                  e.target.files?.item(0)
                );
              }}
            />
            <h3>Result</h3>
            <button
              onClick={() => {
                convertToClip(
                  ffmpeg,
                  video,
                  IMPORTFILENAME,
                  AUDIOFILENAME,
                  CONCATFILENAME,
                  PROCESSEDAUDIOFN,
                  setClip
                );
              }}
            >
              Convert to clip
            </button>
            {clip && (
              <button
                onClick={() => {
                  transcribeClip(ffmpeg, PROCESSEDAUDIOFN);
                }}
              >
                Transcribe
              </button>
            )}
            <button
              onClick={() => {
                cleanClip(
                  ffmpeg,
                  video,
                  IMPORTFILENAME,
                  CONCATFILENAME,
                  PROCESSEDAUDIOFN,
                  setCleanedClip
                );
              }}
            >
              Clean clip
            </button>
            {clip && <video controls width="250" src={clip}></video>}
            {transcription && <p>{JSON.stringify(transcription)}</p>}
            {cleanedClip && (
              <video controls width="250" src={cleanedClip}></video>
            )}
          </div>
        ) : (
          <p>Loading...</p>
        )}
        <div className={styles.grid}></div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by En & Sn
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
